"""Reporter Agent - Generates markdown and PDF reports."""
import logging
from typing import List, Dict
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

class ReporterAgent:
    """Agent responsible for generating opportunity reports."""
    
    def __init__(self, config: dict = None):
        """
        Initialize the Reporter Agent.
        
        Args:
            config: Agent configuration dictionary
        """
        self.config = config or {}
        self.top_n = self.config.get('top_n', 20)
        self.detailed_n = self.config.get('detailed_analysis_n', 10)
    
    def generate_markdown_report(self, products: List[Dict], output_path: str = None) -> str:
        """
        Generate a markdown report with top opportunities.
        
        Args:
            products: List of scored product dictionaries
            output_path: Optional path to save the report
            
        Returns:
            Markdown report content
        """
        logger.info(f"Generating markdown report for {len(products)} products...")
        
        # Sort by score if not already sorted
        products = sorted(products, key=lambda x: x.get('overall_score', 0), reverse=True)
        
        # Get top N products
        top_products = products[:self.top_n]
        
        # Generate report
        report_date = datetime.now().strftime("%Y-%m-%d")
        
        report = f"""# 🚀 Douyin Opportunity Finder - Daily Report
**Generated:** {report_date}  
**Total Opportunities Analyzed:** {len(products)}  
**Top Opportunities:** {len(top_products)}

---

## 📊 Executive Summary

This report identifies trending products on Douyin (Chinese TikTok) that are **NOT yet available** on TikTok Shop US/UK, validated for market potential.

### Key Metrics
- **Products Scanned:** {len(products)}
- **Average Score:** {sum(p.get('overall_score', 0) for p in products) / len(products):.1f}/10 (if products exist)
- **Top Score:** {top_products[0].get('overall_score', 0):.1f}/10 (if top_products else 0)
- **High Potential (8+):** {sum(1 for p in products if p.get('overall_score', 0) >= 8)} products

---

## 🎯 Top {len(top_products)} Opportunities

| Rank | Product Name | Douyin Hot Count | Market Fit Score | Content Angle |
|------|-------------|------------------|------------------|---------------|
"""
        
        for i, product in enumerate(top_products, 1):
            name = product.get('english_title', product.get('title', 'Unknown'))[:40]
            hot_count = f"{product.get('hot_count', 0):,}"
            score = product.get('overall_score', 0)
            analysis = product.get('market_analysis', {})
            content_angle = analysis.get('content_angle', 'N/A')[:50]
            
            # Color-code scores
            if score >= 8:
                score_str = f"🟢 {score}"
            elif score >= 6:
                score_str = f"🟡 {score}"
            else:
                score_str = f"🔴 {score}"
            
            report += f"| {i} | {name} | {hot_count} | {score_str} | {content_angle} |\n"
        
        report += """
---

## 🔍 Detailed Analysis (Top 10)

"""
        
        # Detailed analysis for top 10
        detailed_products = products[:self.detailed_n]
        
        for i, product in enumerate(detailed_products, 1):
            name = product.get('english_title', product.get('title', 'Unknown'))
            hot_count = product.get('hot_count', 0)
            score = product.get('overall_score', 0)
            breakdown = product.get('score_breakdown', {})
            analysis = product.get('market_analysis', {})
            
            report += f"""
### #{i}: {name}

**Overall Score:** {score}/10  
**Douyin Hot Count:** {hot_count:,}

#### Score Breakdown
- 🏆 Competition: {breakdown.get('competition', 'N/A')}/10
- 💬 Sentiment: {breakdown.get('sentiment', 'N/A')}/10
- 🌍 Cultural Fit: {breakdown.get('cultural_fit', 'N/A')}/10
- 📹 Visual Appeal: {breakdown.get('visual_appeal', 'N/A')}/10
- 💰 Price Point: {breakdown.get('price_point', 'N/A')}/10

#### Content Strategy
**Video Idea:** {analysis.get('content_angle', 'N/A')}

#### Notes
{analysis.get('notes', 'No additional notes.')}

---
"""
        
        report += """
## 📝 Action Items

1. **Priority 1 (Score 8-10):** Focus on creating content for top 3 products immediately
2. **Priority 2 (Score 6-7.9):** Research suppliers and prepare content calendar
3. **Priority 3 (Score <6):** Monitor for trends, revisit in 1-2 weeks

## ⚠️ Disclaimer

- Scores are AI-generated estimates based on available data
- Always conduct your own market research before investing
- Product availability and competition change rapidly
- This report is for informational purposes only

---

*Generated by Douyin Opportunity Finder v1.0*
"""
        
        # Save report if path provided
        if output_path:
            output_file = Path(output_path)
            output_file.parent.mkdir(parents=True, exist_ok=True)
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(report)
            logger.info(f"Markdown report saved to {output_file}")
        
        return report
    
    def get_report_summary(self, products: List[Dict]) -> str:
        """Get a brief summary for notifications."""
        if not products:
            return "No opportunities found today."
        
        products = sorted(products, key=lambda x: x.get('overall_score', 0), reverse=True)
        top_product = products[0]
        top_name = top_product.get('english_title', top_product.get('title', 'Unknown'))
        top_score = top_product.get('overall_score', 0)
        
        high_potential = sum(1 for p in products if p.get('overall_score', 0) >= 8)
        
        summary = f"""📊 Daily Opportunity Report Ready!

🎯 Found {len(products)} gap products
⭐ Top pick: "{top_name[:50]}" (Score: {top_score}/10)
🔥 {high_potential} high-potential products (8+)

See attached PDF for full details."""
        
        return summary
